name = "mi-portal-rifas"
main = "functions/api/_worker.js"
compatibility_date = "2025-11-28"

[env.production]
vars = { ENVIRONMENT = "production" }

[[env.production.d1_databases]]
binding = "DB"
database_name = "rifas_db"
database_id = "8975ab02-d5b3-4758-bd7f-d6834d813379"